# Copyright 2016 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM alpine:3.16 AS curl

ADD curl.tar.gz /

COPY third_party/static-curl/mykey.asc /mykey.asc
COPY third_party/static-curl/build.sh /build.sh

RUN /build.sh


FROM debian:11.4 AS jq

ADD jq.tar.gz /

COPY build-jq.sh /build-jq.sh

RUN /build-jq.sh


FROM debian:11.4 as bash

RUN apt-get update
RUN apt-get install -y bash-static


FROM {ARG_FROM}

MAINTAINER Jingyuan Liang <jingyuanliang@google.com>

COPY --from=curl /tmp/release/curl /usr/bin/curl
COPY --from=jq /tmp/release/jq /usr/bin/jq
COPY --from=bash /bin/bash-static /bin/bash

# Add the platform-specific binary.
COPY bin/{ARG_OS}_{ARG_ARCH}/{ARG_BIN} /{ARG_BIN}

# Add third-party licenses.
COPY .licenses/ /LICENSES/

ENV HOME /

ENTRYPOINT ["/{ARG_BIN}"]
